-- This SQL file defines schema for `fishtrack` database

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE DATABASE IF NOT EXISTS `fishtrack`;
USE `fishtrack`;


CREATE TABLE IF NOT EXISTS `Target Profile` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `email` varchar(64) NOT NULL,
  `phone` varchar(16) NOT NULL,
  `company` varchar(64) NOT NULL,
  `JobTitle` varchar(64) NOT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `Attack` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `UniqueRandomCode` varchar(32) DEFAULT NULL,
  `scheme` varchar(32) NOT NULL,
  `target` int NOT NULL,
  PRIMARY KEY (`uid`),
  FOREIGN KEY (`target`) REFERENCES `Target Profile` (`uid`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `Event` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `atk_id` int NOT NULL,
  `kind` varchar(64) DEFAULT NULL,
  `ts` datetime NOT NULL,
  `detail` json NOT NULL,
  PRIMARY KEY (`uid`),
  FOREIGN KEY (`atk_id`) REFERENCES `Attack` (`uid`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
