name: local-test-fish
services:
  db:
    image: mysql:9
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_USER: root
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: fishtrack
      MYSQL_USER: fish_app
      MYSQL_PASSWORD: db_password_for_local_test
    volumes:
    - type: volume
      source: mysql
      target: /var/lib/mysql
    - type: bind
      source: ../../src/database/fishtrack.sql
      target: /opt/fish/fishtrack.sql
      read_only: true
    command:
    - mysqld
    - --init-file
    - /opt/fish/fishtrack.sql
    ports:
    - 3306:3306
    healthcheck:
      test:
      - CMD
      - mysqlsh
      - --user=fish_app
      - --password=db_password_for_local_test
      - --database=fishtrack
      - '--execute=DESCRIBE fishlist;'
      interval: 1s
      timeout: 15s
      retries: 10
  pma:
    image: phpmyadmin:5
    environment:
      PMA_HOST: db
    ports:
    - 8091:80
    links:
    - db
  cli:
    image: fishing-smile
    pull_policy: never
    build:
      context: ../..
    env_file:
    - env/database.env
    entrypoint:
    - sh
    # Mount for live editing while dev
    volumes:
      - type: bind
        source: ../../src
        target: /opt/app/src
    depends_on:
      db:
        condition: service_healthy
    profiles:
    - cli

volumes:
    mysql:
